In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [3]:
df = pd.read_csv('mitbih_test.csv',header=None)

In [4]:
df.describe

<bound method NDFrame.describe of             0         1         2         3         4         5         6    \
0      1.000000  0.758264  0.111570  0.000000  0.080579  0.078512  0.066116   
1      0.908425  0.783883  0.531136  0.362637  0.366300  0.344322  0.333333   
2      0.730088  0.212389  0.000000  0.119469  0.101770  0.101770  0.110619   
3      1.000000  0.910417  0.681250  0.472917  0.229167  0.068750  0.000000   
4      0.570470  0.399329  0.238255  0.147651  0.000000  0.003356  0.040268   
...         ...       ...       ...       ...       ...       ...       ...   
21887  0.928736  0.871264  0.804598  0.742529  0.650575  0.535632  0.394253   
21888  0.802691  0.692078  0.587444  0.446936  0.318386  0.189836  0.118087   
21889  1.000000  0.967359  0.620178  0.347181  0.139466  0.089021  0.103858   
21890  0.984127  0.567460  0.607143  0.583333  0.607143  0.575397  0.575397   
21891  0.973970  0.913232  0.865510  0.823210  0.746204  0.642082  0.547722   

            7    

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21892 entries, 0 to 21891
Columns: 188 entries, 0 to 187
dtypes: float64(188)
memory usage: 31.4 MB


In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X = df.iloc[:,0:187]
y = df[187]

In [8]:
y[y!=0.0] = 1.0

In [9]:
y

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
21887    1.0
21888    1.0
21889    1.0
21890    1.0
21891    1.0
Name: 187, Length: 21892, dtype: float64

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=241)
X_train, X_val, y_train, y_val  = train_test_split(X_train, y_train, test_size=0.2, random_state=241)

In [11]:
X_scaled = preprocessing.scale(X_train)


In [12]:
X_scaled

array([[ 0.45025986,  0.12609626, -0.18721299, ..., -0.09112744,
        -0.08600824, -0.08464612],
       [ 0.38728864,  1.09672184,  1.14635703, ..., -0.09112744,
        -0.08600824, -0.08464612],
       [ 0.45025986,  0.80217331,  1.17865844, ..., -0.09112744,
        -0.08600824, -0.08464612],
       ...,
       [ 0.45025986,  0.19752368, -0.73589196, ..., -0.09112744,
        -0.08600824, -0.08464612],
       [ 0.45025986,  0.74510664,  1.17843858, ..., -0.09112744,
        -0.08600824, -0.08464612],
       [ 0.30994051,  0.85733438,  0.32879893, ..., -0.09112744,
        -0.08600824, -0.08464612]])

In [13]:
from sklearn import svm

In [14]:
clf = svm.SVC()

In [15]:
clf.fit(X_train, y_train)

SVC()

In [16]:
clf.dual_coef_

array([[-1., -1., -1., ...,  1.,  1.,  1.]])

In [17]:
clf.predict(X_test)

array([0., 0., 0., ..., 0., 0., 0.])

In [18]:
from sklearn.metrics import confusion_matrix

In [19]:
confusion_matrix(y_test, clf.predict(X_test))

array([[3627,    4],
       [ 178,  570]], dtype=int64)

In [20]:
4010.0/4379

0.9157341858871888

In [21]:
model2=svm.SVC(kernel='poly')

In [22]:
model2.fit(X_train, y_train)

SVC(kernel='poly')

In [23]:
confusion_matrix(y_test, model2.predict(X_test))

array([[3623,    8],
       [ 184,  564]], dtype=int64)

In [24]:
3631.0/4379

0.8291847453756566

In [25]:
model1=svm.SVC(kernel='linear')

In [26]:
model1.fit(X_train, y_train)

SVC(kernel='linear')

In [27]:
confusion_matrix(y_test, model1.predict(X_test))

array([[3591,   40],
       [ 367,  381]], dtype=int64)

In [28]:
1.0*(3591+381)/4379

0.9070564055720484

In [29]:
model3=svm.SVC(kernel='rbf')

In [30]:
model4=svm.SVC(kernel='sigmoid')
model4.fit(X_train,y_train)


SVC(kernel='sigmoid')

In [31]:
confusion_matrix(y_test, model4.predict(X_test))

array([[3097,  534],
       [ 607,  141]], dtype=int64)

In [32]:
1.0*(3565+314)/4379

0.8858186800639415

In [33]:
candidates = [0.25, 0.5, 1.0, 2.0, 4.0]

In [34]:
candidates

[0.25, 0.5, 1.0, 2.0, 4.0]

In [35]:
model1.get_params

<bound method BaseEstimator.get_params of SVC(kernel='linear')>

In [36]:
model1.coef_

array([[-3.38049034e-01, -8.41838825e-01, -2.06441688e-02,
         6.69566761e-01,  4.92503701e-01,  9.41016606e-01,
         1.35806055e+00,  2.79631796e-01,  2.35285906e+00,
        -2.39189861e+00, -4.55000862e+00, -2.22910532e+00,
         2.18962551e-01,  8.39492753e-01, -1.20614726e+00,
        -5.87746969e-02,  1.49839872e+00,  2.38387075e+00,
         1.93119986e+00, -2.05059578e-01, -7.10927183e-01,
        -6.81039405e-01, -9.86794700e-01, -3.49571364e-01,
         5.07844436e-02,  4.74880488e-01, -3.55284665e-01,
         4.30860653e-01,  3.63836631e-01,  1.76622255e-01,
         1.86666414e-01, -8.30251627e-01, -5.28671392e-01,
         5.96363947e-01,  2.33941347e-01,  1.51235899e-01,
        -1.26465636e-01, -5.52711228e-02,  5.81571529e-01,
        -1.94288297e-01,  3.97996524e-01, -1.79297311e-01,
        -2.63992845e-03, -3.43743166e-02,  1.81571144e-01,
         2.97925896e-01, -3.94421891e-01,  5.75314456e-01,
         1.16072417e-01, -3.39985205e-01,  5.60132482e-0

In [37]:
weights = []

In [38]:
model1.C = 1.0
for c in candidates:
    model1.C = c
    model1.fit(X_train,y_train)
    weights.append(model1.coef_)

In [39]:
print(weights)

[array([[-2.84729867e-01, -7.79748962e-01, -4.61893466e-02,
         5.11408756e-01,  7.20849660e-01,  8.59941781e-01,
         1.24903617e+00,  7.51829410e-01,  9.56826318e-01,
        -1.85864065e+00, -3.24970643e+00, -1.94270035e+00,
        -2.37476118e-01,  2.09484434e-01, -5.60046674e-01,
         9.73514172e-02,  1.00211527e+00,  1.35966679e+00,
         1.01507362e+00,  2.38578729e-01, -5.70192879e-02,
        -2.84579460e-01, -3.63050300e-01, -2.48651936e-01,
        -1.31989793e-01,  4.85625433e-02, -1.01408596e-01,
         6.46581371e-02,  1.03742909e-01,  1.06753332e-01,
         1.10529293e-01, -4.93859570e-01, -1.30156261e-01,
         2.26259689e-01,  1.83462644e-01,  2.16005868e-01,
         3.49328692e-02,  8.54558601e-02,  3.66795393e-01,
        -4.76555889e-03,  1.68266189e-01,  1.83080313e-02,
        -6.62400444e-02,  5.45690241e-03,  1.04053701e-01,
         1.86931244e-01, -6.56012991e-02,  2.75573535e-01,
         9.99970467e-02, -1.25992286e-01,  1.09979371e-

In [42]:
from sklearn.metrics import precision_score
precisions = []
for c in candidates:
    model1.C = c
    model1.fit(X_train, y_train)
    precisions.append(precision_score(y_train, model1.predict(X_train)))
print(precisions)

[0.9070830159939071, 0.9096385542168675, 0.9081481481481481, 0.9024034959941734, 0.8992080633549316]


In [78]:
print(precisions)

[0.0, 0.0, 0.0, 0.9794007490636704, 0.941972920696325, 0.9035856573705179]


In [169]:
from sklearn.metrics import recall_score
recalls = []
for c in candidates:
    model1.C = c
    model1.fit(X_train, y_train)
    recalls.append(recall_score(y_train, model1.predict(X_train)))

In [170]:
print(recalls)

[0.4941908713692946, 0.5012448132780083, 0.5087136929460581, 0.5141078838174273, 0.5182572614107884]


In [81]:
number_of_vectors = []
for c in candidates:
    model1.C = c
    model1.fit(X_train, y_train)
    number_of_vectors.append(model1.n_support_)
print(number_of_vectors)

[array([2410, 2410], dtype=int32), array([2415, 2410], dtype=int32), array([2423, 2410], dtype=int32), array([2416, 2403], dtype=int32), array([2155, 2137], dtype=int32), array([1863, 1823], dtype=int32)]


In [88]:
from sklearn.metrics import zero_one_loss
error_rates_val = []
for c in candidates:
    model1.C = c
    model1.fit(X_train,y_train)
    error_rate = zero_one_loss(y_val, model1.predict(X_val))
    error_rates_val.append(error_rate)


In [89]:
print(error_rates_val)

[0.17584927205252643, 0.17584927205252643, 0.17584927205252643, 0.1393091635740794, 0.11161861261775619, 0.10333999429060803]


In [90]:
from sklearn.metrics import precision_score
precisions_val = []
for c in candidates:
    model1.C = c
    model1.fit(X_train, y_train)
    precisions_val.append(precision_score(y_val, model1.predict(X_val)))

In [91]:
print(precisions_val)

[0.0, 0.0, 0.0, 0.9923076923076923, 0.9707112970711297, 0.934931506849315]


In [93]:
from sklearn.metrics import recall_score
recalls_val = []
for c in candidates:
    model1.C = c
    model1.fit(X_train, y_train)
    recalls_val.append(recall_score(y_val, model1.predict(X_val)))

In [94]:
print(recalls_val)

[0.0, 0.0, 0.0, 0.20941558441558442, 0.37662337662337664, 0.4431818181818182]


In [95]:
from sklearn.metrics import fbeta_score
f_scores = []
for c in candidates:
    model1.C = c 
    model1.fit(X_train,y_train)
    f_scores.append(fbeta_score(y_val, model1.predict(X_val), beta=0.5))

/Users/user/anaconda2/lib/python2.7/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


In [96]:
print(f_scores)

[0.0, 0.0, 0.0, 0.5677816901408451, 0.7379134860050891, 0.7651345291479821]


In [97]:
from sklearn.metrics import fbeta_score
f_scores2 = []
for c in candidates:
    model1.C = c 
    model1.fit(X_train,y_train)
    f_scores2.append(fbeta_score(y_val, model1.predict(X_val), beta=2.0))
print(f_scores2)

[0.0, 0.0, 0.0, 0.24865073245952196, 0.4291527931927488, 0.4952830188679246]


## 11B

In [106]:
candidates_2 = [16.0, 64.0, 128.0, 512.0, 1024.0]

In [107]:
error_rates_2 = []
for c in candidates_2:
    model2.C = c
    model2.fit(X_train,y_train)
    error_rate = zero_one_loss(y_train, model2.predict(X_train))
    error_rates_2.append(error_rate)
print(error_rates_2)

[0.1254104211277659, 0.0982869379014989, 0.07787294789436117, 0.06259814418272658, 0.05546038543897214]


In [132]:
precisions_2 = []
for c in candidates_2:
    model2.C = c
    model2.fit(X_train, y_train)
    precisions_2.append(precision_score(y_train, model2.predict(X_train)))

In [134]:
recalls_2 = []
for c in candidates_2:
    model2.C = c
    model2.fit(X_train, y_train)
    recalls_2.append(recall_score(y_train, model2.predict(X_train)))

In [110]:
number_of_vectors_2 = []
for c in candidates_2:
    model2.C = c
    model2.fit(X_train, y_train)
    number_of_vectors_2.append(model2.n_support_)
print(number_of_vectors_2)

[array([2101, 2074], dtype=int32), array([1899, 1857], dtype=int32), array([1762, 1703], dtype=int32), array([1463, 1372], dtype=int32), array([1351, 1228], dtype=int32)]


In [111]:
error_rates_2_val = []
for c in candidates_2:
    model2.C = c
    model2.fit(X_train,y_train)
    error_rate = zero_one_loss(y_val, model2.predict(X_val))
    error_rates_2_val.append(error_rate)
print(error_rates_2_val)

[0.12960319725949188, 0.09877248073080214, 0.08192977447901795, 0.0690836425920639, 0.06679988581216101]


In [112]:
precisions_2_val = []
for c in candidates_2:
    model2.C = c
    model2.fit(X_train, y_train)
    precisions_2_val.append(precision_score(y_val, model2.predict(X_val)))

In [113]:
recalls_2_val = []
for c in candidates_2:
    model2.C = c
    model2.fit(X_train, y_train)
    recalls_2_val.append(recall_score(y_val, model2.predict(X_val)))

In [114]:
print(precisions_2_val)

[0.9709302325581395, 0.9787234042553191, 0.9824046920821115, 0.9895287958115183, 0.9847715736040609]


In [115]:
print(recalls_2_val)

[0.2711038961038961, 0.44805194805194803, 0.5438311688311688, 0.6136363636363636, 0.6298701298701299]


In [125]:
f_scores_2 = []
for c in candidates_2:
    model2.C = c 
    model2.fit(X_train,y_train)
    f_scores_2.append(fbeta_score(y_val, model2.predict(X_val), beta=2.0))
print(f_scores_2)

[0.3167678300455235, 0.5025491624180626, 0.5971479500891265, 0.6640899508081518, 0.6787963610916725]


In [119]:
error_rates_3 = []
for c in candidates_2:
    model3.C = c
    model3.fit(X_train,y_train)
    error_rate = zero_one_loss(y_train, model3.predict(X_train))
    error_rates_3.append(error_rate)
print(error_rates_3)

[0.06473947180585293, 0.04925053533190582, 0.042683797287651704, 0.032548179871520366, 0.028979300499643146]


In [122]:
precisions_3 = []
for c in candidates_2:
    model3.C = c
    model3.fit(X_train, y_train)
    precisions_3.append(precision_score(y_train, model3.predict(X_train)))
print(precisions_3)

[0.9659020458772474, 0.9761904761904762, 0.9773445732349842, 0.9798624754420432, 0.9775977121067684]


In [137]:
recalls_3 = []
for c in candidates_2:
    model3.C = c
    model3.fit(X_train, y_train)
    recalls_3.append(recall_score(y_train, model3.predict(X_train)))
print(recalls_3)

[0.6464730290456432, 0.7315352697095435, 0.7697095435684648, 0.8278008298755186, 0.8510373443983402]


In [126]:
f_scores_3 = []
for c in candidates_2:
    model3.C = c 
    model3.fit(X_train,y_train)
    f_scores_3.append(fbeta_score(y_val, model3.predict(X_val), beta=2.0))
print(f_scores_3)

[0.6548455056179775, 0.7239348804987878, 0.7528360261258165, 0.8010862186014935, 0.8082516063577951]


In [127]:
error_rates_4 = []
for c in candidates_2:
    model4.C = c
    model4.fit(X_train,y_train)
    error_rate = zero_one_loss(y_train, model4.predict(X_train))
    error_rates_4.append(error_rate)
print(error_rates_4)

[0.13968593861527479, 0.16395431834403995, 0.17194860813704493, 0.17915774446823696, 0.18008565310492508]


In [128]:
precisions_4 = []
for c in candidates_2:
    model4.C = c
    model4.fit(X_train, y_train)
    precisions_4.append(precision_score(y_train, model4.predict(X_train)))
print(precisions_4)

[0.6215780998389694, 0.5257403189066059, 0.5002182453077259, 0.47892074198988194, 0.4763102725366876]


In [129]:
recalls_4 = []
for c in candidates_2:
    model4.C = c
    model4.fit(X_train, y_train)
    recalls_4.append(recall_score(y_train, model4.predict(X_train)))
print(recalls_4)

[0.48049792531120333, 0.47883817427385894, 0.4755186721991701, 0.4713692946058091, 0.4713692946058091]


In [130]:
f_scores_4 = []
for c in candidates_2:
    model4.C = c 
    model4.fit(X_train,y_train)
    f_scores_4.append(fbeta_score(y_val, model4.predict(X_val), beta=2.0))
print(f_scores_4)

[0.47643442622950816, 0.4718239413137713, 0.46250412950115627, 0.4639344262295082, 0.46287209682695446]


In [138]:
error_rates_3_val = []
for c in candidates_2:
    model3.C = c
    model3.fit(X_train,y_train)
    error_rate = zero_one_loss(y_val, model3.predict(X_val))
    error_rates_3_val.append(error_rate)
print(error_rates_3_val)

[0.0725092777619184, 0.0579503282900371, 0.05281187553525546, 0.04396231801313155, 0.04367684841564379]


In [139]:
precisions_3_val = []
for c in candidates_2:
    model3.C = c
    model3.fit(X_train, y_train)
    precisions_3_val.append(precision_score(y_val, model3.predict(X_val)))

In [140]:
recalls_3_val = []
for c in candidates_2:
    model3.C = c
    model3.fit(X_train, y_train)
    recalls_3_val.append(recall_score(y_val, model3.predict(X_val)))

In [143]:
error_rates_4_val = []
for c in candidates_2:
    model4.C = c
    model4.fit(X_train,y_train)
    error_rate = zero_one_loss(y_val, model4.predict(X_val))
    error_rates_4_val.append(error_rate)
print(error_rates_4_val)

[0.14901512988866683, 0.16699971453040252, 0.17670568084499005, 0.1815586640022837, 0.18355695118469884]


In [144]:
precisions_4_val = []
for c in candidates_2:
    model4.C = c
    model4.fit(X_train, y_train)
    precisions_4_val.append(precision_score(y_val, model4.predict(X_val)))
print(precisions_4_val)

[0.6012931034482759, 0.5289719626168224, 0.49733570159857904, 0.48293515358361777, 0.4772344013490725]


In [145]:
recalls_4_val = []
for c in candidates_2:
    model4.C = c
    model4.fit(X_train, y_train)
    recalls_4_val.append(recall_score(y_val, model4.predict(X_val)))
print(recalls_4_val)

[0.45292207792207795, 0.4594155844155844, 0.45454545454545453, 0.4594155844155844, 0.4594155844155844]


## 12

In [155]:
model3.C = 1024.0
model3.fit(X_train, y_train)
error_rate = zero_one_loss(y_test, model3.predict(X_test))
print(error_rate)

0.036766385019410874


In [156]:
print(precision_score(y_test, model3.predict(X_test)))

0.9787928221859706


In [149]:
print(recall_score(y_test, model3.predict(X_test)))

0.4786096256684492


In [150]:
confusion_matrix(y_test, model3.predict(X_test))

array([[3210,  421],
       [ 390,  358]])

In [157]:
fbeta_score(y_test, model3.predict(X_test), beta=0.5)

0.9375

In [158]:
model2.C = 1024.0
model2.fit(X_train, y_train)
error_rate2 = zero_one_loss(y_test, model2.predict(X_test))
print(error_rate2)
print(precision_score(y_test, model2.predict(X_test)))
print(recall_score(y_test, model2.predict(X_test)))
print(fbeta_score(y_test, model2.predict(X_test), beta=0.5)

0.0525234071705869
0.9942748091603053
0.696524064171123


0.9375

In [159]:
print(fbeta_score(y_test, model2.predict(X_test), beta=0.5))

0.9159634317862166


In [161]:
model4.C = 16.0
model4.fit(X_train, y_train)
error_rate4 = zero_one_loss(y_test, model4.predict(X_test))
print(error_rate4)
print(precision_score(y_test, model4.predict(X_test)))
print(recall_score(y_test, model4.predict(X_test)))
print(fbeta_score(y_test, model4.predict(X_test), beta=2.0))

0.14455355103905
0.5944170771756979
0.4839572192513369
0.502638156067759


In [171]:
model1.C = 0.5
model1.fit(X_train, y_train)
error_rate1 = zero_one_loss(y_test, model1.predict(X_test))
print(error_rate1)
print(precision_score(y_test, model1.predict(X_test)))
print(recall_score(y_test, model1.predict(X_test)))
print(fbeta_score(y_test, model1.predict(X_test), beta=2.0))

0.09294359442795164
0.9088729016786571
0.5066844919786097
0.5558814901730714


In [173]:
model1.support_vectors_.size

635052

In [174]:
model2.support_vectors_.size

482273

In [175]:
model3.support_vectors_.size

336787

In [176]:
model4.support_vectors_.size

556699

In [177]:
support_vectors = []
for c in candidates:
    model1.C = c
    model1.fit(X_train, y_train)
    support_vectors.append(model1.support_vectors_.size)
print(support_vectors)

[643841, 635052, 629629, 625702, 620466]


In [178]:
support_vectors2 = []
for c in candidates_2:
    model2.C = c
    model2.fit(X_train, y_train)
    support_vectors2.append(model2.support_vectors_.size)
print(support_vectors2)

[780725, 702372, 647955, 530145, 482273]


In [179]:
support_vectors3 = []
for c in candidates_2:
    model3.C = c
    model3.fit(X_train, y_train)
    support_vectors3.append(model3.support_vectors_.size)
print(support_vectors3)

[526592, 458524, 424116, 364089, 336787]


In [180]:
support_vectors4 = []
for c in candidates_2:
    model4.C = c
    model4.fit(X_train, y_train)
    support_vectors4.append(model4.support_vectors_.size)
print(support_vectors4)

[556699, 506957, 494989, 486948, 485452]
